# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trackingpharma

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_2b7ad17f8efa4b7496173143811c361c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4d3e773353f747e4a9d90bbe936906e8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_2b7ad17f8efa4b7496173143811c361c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trackingpharma'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ded50d0d717b4085af1d394589131ec1 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_2b7ad17f8efa4b7496173143811c361c }}/appsvc/staticsite:${{ github.sha }}'